/* ================= CHESS CONTENT BANK =================
   Item types:
   - "mc": multiple choice (same as math)
   - "board": interactive puzzle. fen = position (white to move),
     solutions = list of accepted [from,to] moves, promo = auto-queen.
*/
const CHESS_MODULES = [
{
  id:"openings", name:"Opening Academy", icon:"📖", color:"#123c63",
  sub:"Named openings & the golden principles", diff:1,
  lesson:"The three golden rules of the opening: <b>1) Control the center</b> (e4/d4/e5/d5), <b>2) Develop knights and bishops quickly</b>, <b>3) Castle early</b> for king safety. Don't move the same piece twice or bring the queen out too soon!",
  items:[
    {type:"mc", diff:1, q:"1.e4 e5 2.Nf3 Nc6 3.Bb5. Which famous opening is this?", choices:["Italian Game","Ruy Lopez (Spanish)","Sicilian Defense","King's Gambit"], ci:1,
     sol:"3.Bb5 attacking the c6-knight is the Ruy Lopez, one of the oldest and most respected openings in chess."},
    {type:"mc", diff:1, q:"1.e4 c5. Black just played the most popular reply to 1.e4 at the top level. What is it called?", choices:["French Defense","Caro-Kann","Sicilian Defense","Scandinavian"], ci:2,
     sol:"1...c5 is the Sicilian Defense. Black fights for the d4-square from the side and plays for a win."},
    {type:"mc", diff:1, q:"1.d4 d5 2.c4. White offers a pawn. What is this opening?", choices:["London System","Queen's Gambit","King's Indian","English Opening"], ci:1,
     sol:"2.c4 is the Queen's Gambit. It's not a true sacrifice: if Black takes with 2...dxc4, White can usually regain the pawn with a strong center."},
    {type:"mc", diff:1, q:"1.e4 e5 2.Nf3 Nc6 3.Bc4. The bishop eyes f7. Which opening is this?", choices:["Italian Game","Ruy Lopez","Scotch Game","Vienna Game"], ci:0,
     sol:"3.Bc4 is the Italian Game. The bishop aims at f7, Black's weakest square in the opening."},
    {type:"mc", diff:1, q:"Which of these is the BEST opening principle to follow?", choices:["Attack with the queen on move 2","Grab as many pawns as possible","Control the center and develop your minor pieces","Move your rook pawns to open lines"], ci:2,
     sol:"Center control + fast development wins the opening battle. Early queen raids and pawn-grabbing lose time."},
    {type:"mc", diff:1, q:"1.e4 e6. Black plans ...d5 next. What defense is this?", choices:["Caro-Kann Defense","French Defense","Pirc Defense","Alekhine Defense"], ci:1,
     sol:"1...e6 is the French Defense. Black builds a strong pawn chain with ...d5, accepting a slightly blocked light-square bishop."},
    {type:"mc", diff:2, q:"The 4-move 'Scholar's Mate' attack targets which square?", choices:["e5","g7","f7","h7"], ci:2,
     sol:"Scholar's Mate (Qh5 + Bc4 hitting f7) targets f7, which is defended only by the king! Defend with ...Nf6 or ...Qe7, and don't try this against strong players."},
    {type:"mc", diff:1, q:"Why should you castle early?", choices:["It develops your queen","It protects your king AND activates a rook","It controls the center","It prevents all checks forever"], ci:1,
     sol:"Castling tucks your king safely in the corner and brings a rook toward the center files: two jobs in one move!"},
    {type:"mc", diff:2, q:"1.d4 Nf6 2.c4 g6. Black prepares to fianchetto the bishop. Which defense is this?", choices:["Grünfeld or King's Indian Defense","Slav Defense","Nimzo-Indian Defense","Dutch Defense"], ci:0,
     sol:"With ...Nf6 and ...g6 Black heads for a King's Indian (or Grünfeld after ...d5): the bishop goes to g7 and strikes the center later."},
    {type:"mc", diff:2, q:"You're White after 1.e4 e5 2.Nf3. Your opponent plays 2...f6? (a weak move). Why is 2...f6 bad?", choices:["It loses a pawn immediately","It weakens the king's diagonal and blocks the knight's best square","It blocks the queen","It allows 3.Bb5"], ci:1,
     sol:"2...f6 weakens the e8–h5 diagonal (inviting sacrifices like Nxe5!) and steals the f6-square from Black's own knight."},
    {type:"mc", diff:1, q:"1.e4 c6. Black prepares ...d5 while keeping the light-squared bishop's diagonal open. What is this defense?", choices:["Caro-Kann Defense","Sicilian Defense","Pirc Defense","French Defense"], ci:0,
     sol:"1...c6 is the Caro-Kann, solid as a rock. Unlike the French, Black's c8-bishop can develop outside the pawn chain."},
    {type:"mc", diff:1, q:"1.e4 d5. Black strikes the center immediately. What is this opening?", choices:["Scandinavian Defense","Alekhine Defense","Modern Defense","Latvian Gambit"], ci:0,
     sol:"1...d5 is the Scandinavian (Center Counter). After 2.exd5 Qxd5 3.Nc3, White gains time attacking the early queen."},
    {type:"mc", diff:2, q:"White plays 1.d4, 2.Nf3, 3.Bf4 and builds the same solid setup almost every game. What is this system called?", choices:["The Colle System","The London System","The Stonewall Attack","The Torre Attack"], ci:1,
     sol:"Bf4 early marks the London System: a low-theory, hard-to-crack setup that's hugely popular from club level to world champions."},
    {type:"mc", diff:2, q:"1.c4, White's first move. What is this opening called?", choices:["The Bird Opening","The English Opening","The Réti Opening","The Catalan"], ci:1,
     sol:"1.c4 is the English Opening, controlling d5 from the side. It often transposes into d4 openings or stays a unique fight."},
    {type:"mc", diff:2, q:"1.d4 Nf6 2.c4 e6 3.Nc3 Bb4. Black pins the knight. Which famous defense is this?", choices:["Queen's Indian Defense","Bogo-Indian Defense","Nimzo-Indian Defense","Ragozin Defense"], ci:2,
     sol:"3...Bb4 is the Nimzo-Indian, one of Black's most respected defenses. Black pressures e4 and may damage White's pawns with ...Bxc3."},
    {type:"mc", diff:3, q:"In the Two Knights Defense, White's famous 'Fried Liver Attack' sacrifices a knight on which square?", choices:["e5","f7","g5","d5"], ci:1,
     sol:"After 1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5 d5 5.exd5 Nxd5?! 6.Nxf7! Kxf7 7.Qf3+. The knight sac on f7 drags the king into the open. Meet 4.Ng5 with 4...d5 and avoid 5...Nxd5!"}
  ]
},
{
  id:"tactics", name:"Tactics Lab", icon:"⚔️", color:"#6b1d3a",
  sub:"Forks, pins, skewers, discoveries & mates", diff:2,
  lesson:"Tactics win games! A <b>fork</b> attacks two things at once. A <b>pin</b> freezes a piece against something more valuable behind it. A <b>skewer</b> is a reversed pin. A <b>discovered attack</b> unleashes a hidden piece. Always look for <b>checks, captures, and threats</b> first!",
  items:[
    {type:"board", diff:2, tag:"Knight Fork", fen:"2q3k1/8/8/3N4/8/8/8/6K1 w - - 0 1",
     q:"White to move: fork the king and queen with one knight jump!",
     solutions:[["d5","e7"]],
     sol:"Ne7+! The knight checks the king on g8 AND attacks the queen on c8. After the king moves, Nxc8 wins the queen. Royal fork!"},
    {type:"board", diff:2, tag:"Skewer", fen:"q7/8/8/k7/8/8/8/1R4K1 w - - 0 1",
     q:"White to move: the king and queen are lined up. Skewer them!",
     solutions:[["b1","a1"]],
     sol:"Ra1+! The check forces the king off the a-file, and then Rxa8 scoops up the queen behind it. That's a skewer: the more valuable piece is hit first."},
    {type:"board", diff:2, tag:"Back-Rank Mate", fen:"6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1",
     q:"White to move: deliver checkmate in ONE move!",
     solutions:[["e1","e8"]], mate:true,
     sol:"Re8#! The black king is trapped behind its own pawns: the classic back-rank mate. Tip: give your king 'luft' (an escape square) with h6 or g6 in your own games."},
    {type:"board", diff:3, tag:"Smothered Mate", fen:"6rk/6pp/8/6N1/8/8/8/6K1 w - - 0 1",
     q:"White to move: the king is smothered by its own pieces. Mate in ONE!",
     solutions:[["g5","f7"]], mate:true,
     sol:"Nf7#! The king on h8 is completely boxed in by its own rook and pawns, and the knight can't be captured. The famous smothered mate!"},
    {type:"board", diff:3, tag:"Double Check", fen:"8/5pkp/3q4/8/3N2P1/8/1B5P/6K1 w - - 0 1",
     q:"White to move: unleash a DOUBLE check that wins the queen!",
     solutions:[["d4","f5"]],
     sol:"Nf5+!! Double check: the knight checks from f5 while opening the b2-bishop's diagonal to g7. Against a double check the king MUST move (no blocking, and g4 guards the knight), and then Nxd6 wins the queen. (Nb5 also hits the queen, but Black could block the single check with ...Qf6.)"},
    {type:"board", diff:1, tag:"Pawn Fork", fen:"4k3/8/2n1n3/8/3P4/8/8/4K3 w - - 0 1",
     q:"White to move: even a humble pawn can fork two knights!",
     solutions:[["d4","d5"]],
     sol:"d5! The pawn attacks both knights at once. Only one can escape, so White wins a piece for at most a pawn."},
    {type:"board", diff:2, tag:"Pin", fen:"3q2k1/5ppp/5n2/6B1/4P3/8/8/6K1 w - - 0 1",
     q:"White to move: the f6-knight is pinned to the queen. Punish it!",
     solutions:[["e4","e5"]],
     sol:"e5! The knight is pinned by the g5-bishop against the queen on d8: if it moves, Bxd8 wins the queen. So the little pawn simply attacks it and wins a piece."},
    {type:"board", diff:3, tag:"Arabian Mate", fen:"r6k/R7/5N2/8/8/8/8/6K1 w - - 0 1",
     q:"White to move: knight and rook team up. Mate in ONE!",
     solutions:[["a7","h7"]], mate:true,
     sol:"Rh7#! The knight on f6 guards both g8 and the rook on h7: the beautiful 'Arabian mate', one of the oldest known mating patterns."},
    {type:"mc", diff:1, q:"A knight on one square attacks both the enemy king and rook. What is this tactic called?", choices:["A pin","A fork","A skewer","A zugzwang"], ci:1,
     sol:"Attacking two (or more) targets at once is a fork. Knights are the most famous forkers because their attacks can't be blocked."},
    {type:"mc", diff:2, q:"What's the difference between a pin and a skewer?", choices:["They are the same thing","A pin freezes a piece in front of a bigger one; a skewer attacks the bigger piece first","A skewer only works with knights","A pin only works on kings"], ci:1,
     sol:"Pin: lesser piece in front, treasure behind (it can't move). Skewer: the big piece is in front, forced to move, exposing the one behind."},
    {type:"mc", diff:2, q:"Why is a DOUBLE check so powerful?", choices:["It wins the queen automatically","The only legal reply is a king move; no blocking or capturing both attackers","It always leads to mate","It skips the opponent's turn"], ci:1,
     sol:"With two pieces checking at once, you can't block or capture both, so the king must move. That's why discovered double checks fuel brilliant combinations."},
    {type:"mc", diff:2, q:"Before every move, strong players scan for 'CCT'. What does it stand for?", choices:["Castle, Capture, Trade","Checks, Captures, Threats","Center, Corners, Tempo","Count, Calculate, Test"], ci:1,
     sol:"Checks, Captures, Threats: the forcing moves. Scan them (for both sides!) on every single turn and you'll stop hanging pieces and start spotting tactics."},
    {type:"board", diff:2, tag:"Queen Fork", fen:"8/6pk/n6p/8/8/8/8/3Q2K1 w - - 0 1",
     q:"White to move: one queen move attacks TWO targets at once!",
     solutions:[["d1","d3"]],
     sol:"Qd3+! The queen checks the king on h7 along the diagonal AND attacks the loose knight on a6 along the same line extended. Whatever Black does about the check, Qxa6 follows. Loose pieces drop off!"},
    {type:"board", diff:3, tag:"Discovered Check", fen:"4k3/p6p/8/4N3/3q4/8/8/4R2K w - - 0 1",
     q:"White to move: move the knight with devastating effect!",
     solutions:[["e5","f3"]],
     sol:"Nf3+! Moving the knight unleashes the e1-rook's check AND the knight attacks the queen on d4. If Black blocks with the queen on the e-file, the rook simply captures it; if the king moves, Nxd4. The queen is lost either way."},
    {type:"board", diff:3, tag:"Anastasia's Mate", fen:"8/4N1pk/8/8/8/8/6K1/R7 w - - 0 1",
     q:"White to move: the knight controls the escape squares. Mate in ONE!",
     solutions:[["a1","h1"]], mate:true,
     sol:"Rh1#! The e7-knight covers both g8 and g6, the g7-pawn blocks its own king, and the rook delivers mate down the h-file. This pattern is called Anastasia's mate; it appears constantly in real games."},
    {type:"board", diff:3, tag:"Boden's Mate", fen:"2kr4/3p4/1p6/8/5B2/8/4B3/6K1 w - - 0 1",
     q:"White to move: two bishops slice the board in a deadly crisscross. Mate in ONE!",
     solutions:[["e2","a6"]], mate:true,
     sol:"Ba6#! The bishops form a lethal X: one checks from a6, the other covers b8 and c7, and the king's own rook and pawn seal the cage. Boden's mate: the classic punishment for a queenside-castled king."},
    {type:"board", diff:2, tag:"Epaulette Mate", fen:"2rkr3/5ppp/8/8/8/Q7/8/6K1 w - - 0 1",
     q:"White to move: the king's own rooks are its downfall. Mate in ONE!",
     solutions:[["a3","d6"]], mate:true,
     sol:"Qd6#! The rooks on c8 and e8 sit like epaulettes on the king's shoulders, blocking both escape squares, while the queen covers c7, d7, and e7. The famous epaulette mate!"},
    {type:"mc", diff:3, q:"What is a 'zwischenzug' (in-between move)?", choices:["A move that passes the turn","An unexpected forcing move inserted before the 'obvious' recapture","A move that offers a draw","Castling in the middlegame"], ci:1,
     sol:"Instead of automatically recapturing, you slip in a bigger threat first (often a check), and only then recapture. One of the most common ways strong players win material."}
  ]
},
{
  id:"endgames", name:"Endgame Empire", icon:"👑", color:"#3f4d10",
  sub:"Basic mates, promotion & key techniques", diff:2,
  lesson:"Endgames decide championships! Learn the basic mates (K+Q, K+R), the <b>opposition</b> in king-and-pawn endings, the <b>square rule</b> for catching passed pawns, and the two rook-endgame pillars: <b>Lucena</b> (winning) and <b>Philidor</b> (drawing).",
  items:[
    {type:"board", diff:1, tag:"Queen Mate", fen:"7k/8/6K1/8/8/8/8/1Q6 w - - 0 1",
     q:"White to move: king and queen work together. Mate in ONE!",
     solutions:[["b1","b8"]], mate:true,
     sol:"Qb8#! The queen checks along the 8th rank while your king covers g7 and h7. Teamwork: the queen can never mate alone."},
    {type:"board", diff:1, tag:"Rook Mate", fen:"k7/8/1K6/8/8/8/8/7R w - - 0 1",
     q:"White to move: the classic king + rook mate. Mate in ONE!",
     solutions:[["h1","h8"]], mate:true,
     sol:"Rh8#! The rook checks along the back rank and your king guards a7 and b7. This 'box method' finish is a must-know."},
    {type:"board", diff:1, tag:"Promotion", fen:"8/P6k/8/8/8/8/8/K7 w - - 0 1",
     q:"White to move: push your passed pawn to glory!",
     solutions:[["a7","a8"]], promo:true,
     sol:"a8=Q! A pawn reaching the last rank becomes a queen (or any piece you choose). Passed pawns must be pushed!"},
    {type:"mc", diff:2, q:"In king-and-pawn endgames, what is 'the opposition'?", choices:["Facing the enemy king with one square between, forcing THEM to move away","Putting your king behind your pawn","Attacking the opponent's pawns","Trading all the pieces"], ci:0,
     sol:"Kings facing off with one square between them: whoever must move loses ground. Grabbing the opposition often decides whether a pawn promotes."},
    {type:"mc", diff:3, q:"The Lucena position is the most important WINNING rook endgame. What's the famous technique?", choices:["Trade the rooks immediately","'Building a bridge': shielding your king from checks with your rook","Sacrificing the pawn","Perpetual check"], ci:1,
     sol:"In Lucena, your pawn is one step from queening but your king is in the way. You 'build a bridge': place the rook on the 4th rank so it can block the enemy rook's checks while your king steps out."},
    {type:"mc", diff:3, q:"The Philidor position is the key DRAWING rook endgame. What's the defensive idea?", choices:["Keep your rook on the 3rd rank until the pawn advances, then check from behind forever","Chase the enemy king with checks immediately","Put your rook in front of the pawn","Trade into a pawn endgame"], ci:0,
     sol:"Philidor's defense: park your rook on your 3rd rank so the enemy king can't advance. Once the pawn steps forward, swing the rook behind for endless checks; the king has no shelter."},
    {type:"mc", diff:2, q:"The 'rule of the square' tells you whether...", choices:["a knight can stop a pawn","your king can catch a runaway passed pawn without counting moves","the position is a draw","you should trade queens"], ci:1,
     sol:"Draw a square from the pawn to its promotion rank. If the defending king can step inside that square, it catches the pawn. If not, the pawn queens!"},
    {type:"mc", diff:2, q:"When you're ahead in material, what's the golden endgame rule?", choices:["Trade PIECES, keep pawns: simplify toward a won pawn endgame","Trade pawns, keep pieces","Avoid all trades","Push your king to the corner"], ci:0,
     sol:"Ahead in material? Trade pieces, not pawns. Fewer pieces means fewer tricks, and your extra material shines. (Behind? Do the opposite and trade pawns!)"},
    {type:"board", diff:2, tag:"Rule of the Square", fen:"7k/8/8/p7/5K2/8/8/8 w - - 0 1",
     q:"White to move: the black pawn is racing to promote. Step into the SQUARE to catch it!",
     solutions:[["f4","e4"],["f4","e3"],["f4","e5"]],
     sol:"Draw the square from a5 to a1 to e1 to e5. Your king must step inside it: Ke4, Ke5, or Ke3 all catch the pawn (verified: any other move and the pawn queens!). No counting needed; just see the square."},
    {type:"mc", diff:3, q:"You have king + rook-pawn (a- or h-file) + the WRONG-colored bishop vs a lone king in the corner. What's the result?", choices:["Always winning","A draw; the defender sits in the promotion corner forever","Winning only with the opposition","Depends on the 50-move rule"], ci:1,
     sol:"If your bishop doesn't control the promotion corner's color, the defending king parks there and you can never evict it; stalemate tricks hold the draw. One of the most famous 'fortress' draws."},
    {type:"mc", diff:2, q:"What is stalemate?", choices:["A position repeated three times","The side to move has NO legal moves but is NOT in check; the game is a draw","Checkmate with a pawn","When only kings remain"], ci:1,
     sol:"No legal moves + not in check = stalemate = draw. When you're winning big, always check you're not giving the enemy king 'no moves'; countless wins have evaporated this way!"},
    {type:"mc", diff:3, q:"Which of these material advantages CANNOT force checkmate against a lone king?", choices:["King + queen","King + rook","King + two bishops","King + two knights"], ci:3,
     sol:"Two knights cannot force mate; the defender always has an escape (mate can only happen if the defender blunders into it). Q, R, and the two bishops all win with correct technique."},
    {type:"mc", diff:2, q:"In a king-and-pawn endgame, where does your king ideally want to be relative to your passed pawn?", choices:["Behind it, pushing from the back","IN FRONT of it, clearing the path","Beside it at all times","As far away as possible"], ci:1,
     sol:"King in FRONT of the pawn (with the opposition) is the classic winning setup: the king clears the road and the pawn follows. King behind the pawn often only draws."}
  ]
},
{
  id:"strategy", name:"Strategy Summit", icon:"🏔️", color:"#4a2a63",
  sub:"Middlegame plans, pawns & piece power", diff:3,
  lesson:"Strategy is what you do when there's no tactic. Evaluate: <b>king safety, piece activity, pawn structure</b>. Rooks crave <b>open files</b>, knights crave <b>outposts</b>, and bishops crave <b>open diagonals</b>. Every pawn move creates a strength AND a weakness.",
  items:[
    {type:"mc", diff:2, q:"What is an 'outpost' for a knight?", choices:["Any central square","A protected square in enemy territory that no enemy pawn can ever attack","A square next to the enemy king","The starting square"], ci:1,
     sol:"An outpost (like a knight on d5 supported by your e4-pawn, with no enemy c- or e-pawn to chase it) turns a knight into a monster worth more than a bishop."},
    {type:"mc", diff:2, q:"Where do rooks belong in the middlegame?", choices:["On open or half-open files","Behind their own pawns","In front of the king","On the edge of the board"], ci:0,
     sol:"Rooks need open lines to breathe. Doubling rooks on an open file and invading the 7th rank is one of the most powerful plans in chess."},
    {type:"mc", diff:2, q:"What makes a bishop 'bad'?", choices:["It's on the wrong color square","Its own pawns are fixed on the same color as the bishop, blocking it","It hasn't moved yet","It's worth less than a knight"], ci:1,
     sol:"A bishop staring at its own pawn chain is 'bad': a big pawn in disguise. Fix your pawns on the OPPOSITE color of your bishop."},
    {type:"mc", diff:3, q:"Which piece is usually stronger in a CLOSED position with locked pawn chains?", choices:["The bishop","The knight","The rook","They're always equal"], ci:1,
     sol:"Knights jump over blockades; bishops hit walls. Closed position → knight. Open position → bishop (and the bishop PAIR is even better)."},
    {type:"mc", diff:3, q:"According to classic strategy, where should you attack a pawn chain?", choices:["At its head","At its base","In the middle","Never attack a pawn chain"], ci:1,
     sol:"Strike the base: the pawn that supports everything. Knock out the foundation and the whole chain crumbles (Nimzowitsch's famous rule)."},
    {type:"mc", diff:2, q:"Why are doubled pawns usually a weakness?", choices:["They can't move at all","They can't defend each other and cover fewer squares","They block the queen","They're worth half a pawn each"], ci:1,
     sol:"Doubled pawns can't protect each other and often can't create a passed pawn. But it's not absolute; sometimes the open file you get in return is worth it!"},
    {type:"mc", diff:3, q:"What is an 'isolated' pawn?", choices:["A pawn with no friendly pawns on adjacent files","A pawn that has been passed","A pawn on the edge","A doubled pawn"], ci:0,
     sol:"No neighbors means no pawn can ever defend it, so pieces get tied down babysitting. But it can also grant open lines and outposts, so it's a double-edged sword."},
    {type:"mc", diff:3, q:"When is it usually GOOD to trade queens?", choices:["When you're ahead in material or the enemy queen threatens your king","Never; the queen is too valuable","Whenever possible","Only in the opening"], ci:0,
     sol:"Trade queens when ahead in material (simplify!) or when your king is the one in danger. Keep queens on when YOU are the attacker."},
    {type:"mc", diff:2, q:"What is a 'passed pawn'?", choices:["A pawn that has crossed the middle of the board","A pawn with no enemy pawns able to block or capture it on its way to promotion","A pawn defended by another pawn","A pawn that just moved two squares"], ci:1,
     sol:"No enemy pawns in front on its file or adjacent files, so nothing but pieces can stop it. 'Passed pawns must be pushed!'"},
    {type:"mc", diff:3, q:"You have the two bishops against bishop + knight. What kind of position should you aim for?", choices:["A locked, closed position","An open position with pawns traded","A position with all pawns on one side","It doesn't matter"], ci:1,
     sol:"The bishop pair loves open boards where both bishops rake long diagonals. Open the position and the 'minor exchange' becomes a real advantage."},
    {type:"mc", diff:3, q:"Tarrasch's famous rule: where do rooks belong relative to passed pawns?", choices:["In front of them","BEHIND them, yours AND the enemy's","Beside them","On the same rank"], ci:1,
     sol:"'Rooks belong behind passed pawns.' Behind your own pawn, the rook gains scope as it advances; behind the enemy's, it permanently harasses. In front, the rook gets buried."},
    {type:"mc", diff:2, q:"In the endgame, how should your king's role change?", choices:["Stay hidden in the corner","Become an ACTIVE fighting piece marching to the center","Shadow the enemy king","Guard the back rank"], ci:1,
     sol:"With queens off, the king transforms from a liability into a warrior worth roughly a minor piece. Centralize it! King activity decides most pawn endgames."},
    {type:"mc", diff:3, q:"What is 'prophylaxis' in chess?", choices:["Trading into an endgame","Preventing your opponent's plan BEFORE pushing your own","A type of gambit","Repeating moves to gain time"], ci:1,
     sol:"Prophylactic thinking asks 'what does my opponent want?', then stops it first. Moves like h3 (preventing ...Bg4) or Kb1 (safety first) are quiet but championship-winning."},
    {type:"mc", diff:2, q:"What does a 'space advantage' actually give you?", choices:["Extra material","More room to maneuver pieces; the cramped side struggles to coordinate","Automatic checkmate","Better pawn structure"], ci:1,
     sol:"More space = your pieces flow between wings faster than your opponent's. The cramped side's classic remedy is trading pieces, so if you have space, avoid trades!"},
    {type:"mc", diff:3, q:"What is a 'hole' or 'weak square'?", choices:["A square no pawn can ever defend: a permanent home for enemy pieces","Any empty square","A square in front of a passed pawn","The square the king castled from"], ci:0,
     sol:"Once the guarding pawns have advanced past or been traded, that square is weak forever. A knight planted in a hole (like d5 or f5) can dominate an entire game."},
    {type:"mc", diff:3, q:"The 'principle of two weaknesses' says winning usually requires...", choices:["two extra pawns","attacking two separate weaknesses so the defense is stretched too thin","two open files","doubling the opponent's pawns twice"], ci:1,
     sol:"One weakness can usually be defended. Create a SECOND one on the other wing and switch attacks between them; the defender's pieces can't be everywhere at once."}
  ]
}
];
