/* ================= PWA: install, offline cache, updates =================
   The service worker (sw.js, generated by assemble.py with a build hash)
   caches the whole app so it opens instantly and works with no connection.
   Registration only happens on https or localhost; opening the HTML file
   directly keeps working exactly as before, with no worker involved.
   initPWA() is called from part4's boot. */

function pwaEligible() {
  return "serviceWorker" in navigator &&
    (location.protocol === "https:" || location.hostname === "localhost" || location.hostname === "127.0.0.1");
}

function initPWA() {
  if (!pwaEligible()) return;
  let reloaded = false;
  navigator.serviceWorker.addEventListener("controllerchange", () => {
    if (reloaded) return;
    reloaded = true;
    location.reload();
  });
  navigator.serviceWorker.register("./sw.js").then(reg => {
    if (reg.waiting && navigator.serviceWorker.controller) showUpdateBar(reg.waiting);
    reg.addEventListener("updatefound", () => {
      const w = reg.installing;
      if (!w) return;
      w.addEventListener("statechange", () => {
        if (w.state === "installed" && navigator.serviceWorker.controller) showUpdateBar(w);
      });
    });
  }).catch(() => {});
  homeScreenTip();
}

/* a small fixed bar, shown only when a fresh version has finished downloading */
function showUpdateBar(worker) {
  if (document.getElementById("updbar")) return;
  const bar = document.createElement("div");
  bar.id = "updbar";
  bar.innerHTML = '<span>A new version of MindMasters is ready.</span>' +
    '<button class="btn gold small" id="updGo">Update now</button>' +
    '<button class="btn ghost small" id="updLater">Later</button>';
  document.body.appendChild(bar);
  document.getElementById("updGo").addEventListener("click", () => {
    document.getElementById("updGo").disabled = true;
    worker.postMessage("SKIP_WAITING");
  });
  document.getElementById("updLater").addEventListener("click", () => bar.remove());
}

/* iPhones and iPads quietly delete a website's saved data after 7 days
   without a visit, unless the site is installed on the Home Screen. Nudge
   once, after onboarding, so progress stays safe. */
function homeScreenTip() {
  const iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) ||
    (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1);
  const standalone = window.matchMedia("(display-mode: standalone)").matches || window.navigator.standalone === true;
  if (!iOS || standalone) return;
  if (typeof S === "undefined" || !S || !S.onboarded || S.a2hsTip) return;
  S.a2hsTip = 1;
  save();
  setTimeout(() => {
    toast("📌", "Tip: tap Share, then Add to Home Screen. MindMasters becomes an app and your saved progress is protected.");
  }, 2500);
}
